#!/usr/bin/env node
/**
 * @clawd/create-agent-auth — one-shot Clawd Agent Auth installer
 * Usage: npx @clawd/create-agent-auth
 */
import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";

const GREEN = "\x1b[32m";
const CYAN = "\x1b[36m";
const PURPLE = "\x1b[35m";
const BOLD = "\x1b[1m";
const RESET = "\x1b[0m";

const log = (msg) => console.log(`${CYAN}▶${RESET} ${msg}`);
const ok = (msg) => console.log(`${GREEN}✓${RESET} ${msg}`);
const header = (msg) => console.log(`\n${BOLD}${PURPLE}${msg}${RESET}\n`);

header("Clawd Agent Auth — CAAP/1.0 Installer");

log("Detecting package manager...");
const pm = existsSync("pnpm-lock.yaml") ? "pnpm" : existsSync("yarn.lock") ? "yarn" : "npm";
ok(`Using ${pm}`);

const install = (pkgs) => {
  const cmd = pm === "pnpm" ? `pnpm add ${pkgs}` : pm === "yarn" ? `yarn add ${pkgs}` : `npm install ${pkgs}`;
  log(`Running: ${cmd}`);
  execSync(cmd, { stdio: "inherit" });
};

log("Installing server packages...");
install("better-auth @better-auth/agent-auth");

log("Installing Solana packages...");
install("better-auth-solana @clawd/agent-auth-solana @solana/kit");

log("Installing client SDK...");
install("@auth/agent");

ok("All packages installed!");

const authTs = `// lib/auth.ts — generated by @clawd/create-agent-auth
import { betterAuth } from "better-auth";
import { siws } from "better-auth-solana";
import { agentAuth } from "@better-auth/agent-auth";
import { createCaapPlugin } from "@clawd/agent-auth-solana";

export const auth = betterAuth({
  plugins: [
    siws({ domain: process.env.BETTER_AUTH_URL?.replace("https://", "") ?? "localhost" }),
    createCaapPlugin({
      heliusApiKey: process.env.HELIUS_API_KEY,
      clawdMint: process.env.CLAWD_TOKEN_ADDRESS ?? "8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump",
      enableSubscriptionTiers: true,
      enableDasAttestation: true,
    }),
    agentAuth({
      capabilities: [
        { name: "attest_agent", description: "Attest a Solana agent identity on-chain" },
        { name: "get_peer_card", description: "Fetch a verified agent peer card" },
      ],
    }),
  ],
});
`;

const envExample = `# Clawd Agent Auth — Environment Variables
# Generated by @clawd/create-agent-auth

BETTER_AUTH_SECRET=               # openssl rand -base64 32
BETTER_AUTH_URL=http://localhost:3000
DATABASE_URL=postgresql://...

HELIUS_API_KEY=                   # helius.dev — free tier works
CLAWD_TOKEN_ADDRESS=8cHzQHUS2s2h8TzCmfqPKYiM4dSt4roa3n7MyRLApump
HELIUS_WEBHOOK_SECRET=            # optional: real-time wallet monitoring
`;

if (!existsSync("lib")) mkdirSync("lib", { recursive: true });
if (!existsSync("lib/auth.ts")) {
  writeFileSync("lib/auth.ts", authTs);
  ok("Created lib/auth.ts");
} else {
  log("lib/auth.ts already exists — skipping");
}

if (!existsSync(".env.example")) {
  writeFileSync(".env.example", envExample);
  ok("Created .env.example");
}

header("Setup complete! 🎉");
console.log(`Next steps:
  1. Copy .env.example → .env.local and fill in your values
  2. Get a free Helius API key at ${CYAN}https://dashboard.helius.dev${RESET}
  3. Add auth routes: ${CYAN}app/api/auth/[...all]/route.ts${RESET}
  4. View the live demo: ${PURPLE}https://x402.wtf/agentauth${RESET}

Docs: ${CYAN}https://github.com/Solizardking/agent-auth${RESET}
`);
